plugins { id 'com.android.application' }

android {
    namespace 'com.daviloza.cavernia'
    compileSdk 34

    defaultConfig {
        applicationId "com.daviloza.cavernia"   // cámbialo si quieres otro ID
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-ads:23.3.0'  // AdMob
    implementation 'com.android.billingclient:billing:7.1.1'          // compras en Play
}
